#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'key' : 'value', 'firstname' : 'Tao', 'lastname' : 'Feng' }
r = requests.post(url, data=payload)

print r.status_code
print r.text
